baseURL = 'https://peasantcoding.github.io'
languageCode = 'zh'
title = 'Solarhub 帮助中心'
theme = "docsy"
contentDir = "content/zh/docs/web"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true
publishDir = "docs"
[languages]
[languages.zh]
languageName ="中文"
title = "Soalrhub 帮助中心"
weight = 1
contentDir = "content/zh"
[languages.en]
languageName ="English"
title = "Solarhub Help Center"
weight = 2
contentDir = "content/en"

[params]
mainMenu = ["docs"]
copyright = "Copyright © 2024 RaymonIoT. All Rights Reserved."
[markup]
  defaultMarkdownHandler = 'goldmark'
[markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[params.ui]
sidebar_menu_compact = true
ul_show = 1
sidebar_menu_foldable = true

[params.search.algolia]
appId = "AU7590UZW9"
apiKey = "542b501d6e1956d4c1889d77e46fb8d8"
indexName = "peasantcodingio"

